language: android

jdk:
  - oraclejdk8

android:
  components:
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-26.0.0
    - android-25

script: 
    - chmod +x deploy.sh
    - chmod +x configure.sh
    - chmod +x buildReleaseApp.sh
    - . deploy.sh

notifications: 
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $ANDROID_HOME
