language: android

jdk:
  - oraclejdk8

android:
  components:
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-26.0.0
    - android-25

notifications: 
  email: true
